### ISSUE TITLE
Error: when installing on 4.1.3

### ISSUE THREAD

**Issue by meersicht** [brunobaudry/moodle-local_deepler#24]
In the course clicking on DeepL Translator button:
Fehler: local_deepler\data\course_data::__construct(): Argument #3 ($context) must be of type core\context, context_course given, called in [dirroot]/local/deepler/translate.php on line 97

Plugin version, latest from Github on 26.6.24

**Comment by brunobaudry** [comment]
thanks for reporting it should be fixed.

**Comment by brunobaudry** [comment]
closed
