### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by kalebheitzman** [brunobaudry/moodle-local_deepler#28]
Hey there, 

I'm the creator of the original plugin and just wanted to make sure you're aware of the major security issue in this plugin. The code in question is in ```externallib.php```. 

```php
public static function get_field($data) {
        global $CFG, $DB;

        $params = self::validate_parameters(self::get_field_parameters(), ['data' => $data]);
        $transaction = $DB->start_delegated_transaction();
        $response = [];

        foreach ($params['data'] as $data) {
            // Check for null values and throw errors.

            // Security checks.
            $context = context_course::instance($data['courseid']);
            self::validate_context($context);
            require_capability('local/deepler:edittranslations', $context);

            // Get the original record.
            $record = (array) $DB->get_record($data['table'], ['id' => $data['id']]);
            $text = $record[$data['field']];

            $response[] = ['text' => $text];
        }

        // Commit the transaction.
        $transaction->allow_commit();

        return $response;
    }
```

This is the function used by the web service and if someone gets improper access to the web service (exposed accidentally, improper setup, etc), it exposes all of this data without constraint to someone. Its unfortunately an easy way to allow someone to edit almost any field in the database and the webservice really needs rewritten with constraints. I can't recommend anyone use this plugin or the deprecated one until this resolved. It's a security incident waiting to happen.

**Comment by brunobaudry** [comment]
Hi @kalebheitzman,
Glad to hear from you at last and many thanks for the feedback !
We are aware of the security issue.

For people wanting to try this plugin :
For this the breach to happpen would mean several pitfalls while administrating Moodle, admin granting translator's right to harmful person etc.

We will work on addin constraints soon.

**Comment by brunobaudry** [comment]
New external services implemented with an additional moodle/course:manageactivities capability check and tighter params checks.

**Comment by kalebheitzman** [comment]
I had a chance to look through the improvements on this and they look great!

**Comment by brunobaudry** [comment]
Thanks @kalebheitzman !
