### ISSUE TITLE
incorrect lang string file.

### ISSUE THREAD

**Issue by danmarsden** [brunobaudry/moodle-local_deepler#30]
string concatenation in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by brunobaudry** [comment]
Thanks for reporting Dan. It is corrected now.
