### ISSUE TITLE
Missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [brunobaudry/moodle-local_deepler#31]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data in a number of tables which will need to be included in the privacy api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy# 

Note that as your plugin integrates with an external api this is a blocker for plugsin db approval.

**Comment by brunobaudry** [comment]
Thanks for your comment Dan and suggestion to implement the Privacy API.

Privacy API is now implemented with the null_provider.
The plugin doesn't store any personal data. 
When callling the Deepl API no personal data is sent. Only translation of the text fields in Moodle core activities or activity plugins. So the GRPD claims should be fullfield by Moddle's core or the activities plugin.
